### ISSUE TITLE
Small problems detected

### ISSUE THREAD

**Issue by mingodad** [cbuttner/tree-sitter-c3#1]
See here https://github.com/zweimach/tree-sitter-c3/issues/5 a list of small problems that this parser/grammar have.
This repository seems to be a clone of https://github.com/zweimach/tree-sitter-c3 probably both of you could cooperate to develop it.

**Comment by cbuttner** [comment]
Thanks for the fixes and improvements.

I don't see how this project is a clone though, it's a completely new from-scratch implementation.

Also, some rules are not too strict on purpose, because the point is not to check for maximal correctness. That should be the compiler's job.

**Comment by zweimach** [comment]
This project is not a clone of https://github.com/zweimach/tree-sitter-c3. It completely covers C3 grammar.  
Awesome work @cbuttner.  

Are you using Neovim? Do you mind if I add this parser to https://github.com/nvim-treesitter/nvim-treesitter?

**Comment by cbuttner** [comment]
Thank you. Feel free to add it to your editor of choice. I'm working on a c3-ts-mode for (Doom) Emacs which is already looking pretty good. Do you already have queries written for Neovim?

Also I'm thinking before this is linked into other projects/editor plugins, maybe we could move this repo to the official C3 org so it has a more "official" URL, if @lerno is cool with that.

**Comment by lerno** [comment]
Yes, that is fine.

**Comment by cbuttner** [comment]
@zweimach Can you check out the new `highlights.scm` file for Neovim?
I think we can add to nvim-treesitter soon.
